Historical Dividends API
the error changed to

  File "C:\Users\lauta\OneDrive\Lautaro\2021\portfolio\software\eod-data\eod\historical_prices\historical_psd.py", line 17, in __init__
    super().__init__(api_key, timeout, '')

TypeError: __init__() takes 3 positional arguments but 4 were given